name: Daily News Crawler

on:
  schedule:
    - cron: '59 0 * * *'  # UTC 기준 → KST 오전 9시 59분
  workflow_dispatch: 

jobs:
  crawl-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create .env file
      run: |
        echo "NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }}" >> .env
        echo "NAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }}" >> .env

    - name: Run news fetcher
      run: |
        python main.py

    - name: Commit and push if there are changes
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add logs/
        git diff --cached --quiet || (git commit -m "뉴스 크롤링 결과 저장 (매일 10시)" && git push)
