name: Daily News Crawler

on:
  schedule:
    - cron: '30 0 * * *'  # KST 오전 9:30
  workflow_dispatch:

jobs:
  crawl-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file
        run: |
          echo "NAVER_CLIENT_ID=${{ secrets.NAVER_CLIENT_ID }}"   >> .env
          echo "NAVER_CLIENT_SECRET=${{ secrets.NAVER_CLIENT_SECRET }}" >> .env
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}"       >> .env  # 공인 IP로 교체
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}"       >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}"       >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}"       >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env

      - name: Run news fetcher
        run: python main.py

      - name: Commit and push if changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git diff --cached --quiet || (git commit -m "자동: 뉴스 크롤링 및 DB 삽입 (매일 9시 30분)" && git push)
